### ISSUE TITLE
Underdogs Brought Over

### ISSUE THREAD

**Issue by luetkemj** [luetkemj/mcdc#12]
Get back marissa

**Comment by headcomic** [comment]
So there have been some delays on the site launch, so I am thinking it might be a good idea for mark to prep for the re-cloning of the Underdog forums and the deploying them on the underdogforums.makingcomics.com space

Last time there were complications that came up because we were not all synchronized in the attempt to do this, so I figure we should start talking here about synchronizing.

From what I can tell the order of operations is: 

1) We choose a date & time for this to be done 

2) Mark clones the site 

3) Once the new site is cloned webcomicunderdogs.com URL gets redirected to the new URL on the MakingCOmics.com space. 

4) Announcements are made to the community regarding the new site space

**Comment by headcomic** [comment]
Done
